version: '3.8'

services:

  # # This is the postgres docker DB available at port 35432
  # #   - This only for local usage and has no bearing on CloudSQL
  # #   - When referencing the db from a compose container, use database:5432
  # #   - When referencing the db from an external process, use localhost:35432
  database:
    image: "postgres:10.16"
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=rainbow_database
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database-data:
